name: Release
on:
  # can be triggered manually
  workflow_dispatch:
  # on master merge
  push:
    branches:
      - master

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:nowatch
      - name: Semantic Release
        run: npx semantic-release
        extra_plugins: |
          @semantic-release/changelog@6.0.0
          @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  storybook-deploy:
    name: Storybook deploy
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install
        run: npm ci
      - name: Deploy
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: storybook-deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: dataesr/mm-notifier-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          mattermost_channel: bots
          deployment_url: https://dataesr.github.io/react-dsfr
